### ISSUE TITLE
Composer Bridge

### ISSUE THREAD

**Issue by szepeviktor** [phar-io/phive#263]
This is my idea.

One adds the Phive Composer repo to `composer.json`

```yaml
  "repositories": [
    {
      "type": "composer",
      "url": "https://phive-repository.org"
    }
  ]
```

Then `composer install phive/phpunit` installs a single phar file package into `vendor/` and links the phar file in `vendor/bin/`

Please comment!
